import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ReduxProvider from "@/redux/ReduxProvider";
import TopMenu from "@/components/TopMenu"; // นำเข้า TopMenu

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dog Slayer App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-900`}>
        <ReduxProvider>
          <NextAuthProvider>
            <TopMenu /> {/* ใส่เมนูไว้ตรงนี้ */}
            
            {/* เว้นช่องว่างด้านบนเท่ากับความสูง TopMenu (16) ในทุกๆ หน้า */}
            <div className="mt-16">
               {children}
            </div>

          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}